/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RastrearTokenRouteImport } from './routes/rastrear.$token'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFinancialRouteImport } from './routes/admin.financial'
import { Route as AdminDeliverersRouteImport } from './routes/admin.deliverers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AuthenticatedTimeRouteImport } from './routes/_authenticated/time'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPacotesRouteImport } from './routes/_authenticated/pacotes'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'
import { Route as AuthenticatedGanhosRouteImport } from './routes/_authenticated/ganhos'
import { Route as AuthenticatedEntregadoresRouteImport } from './routes/_authenticated/entregadores'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedPacotesDistribuirAlocacaoIdRouteImport } from './routes/_authenticated/pacotes.distribuir.$alocacaoId'
import { Route as AuthenticatedPacotesAlocarOperacaoIdRouteImport } from './routes/_authenticated/pacotes.alocar.$operacaoId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RastrearTokenRoute = RastrearTokenRouteImport.update({
  id: '/rastrear/$token',
  path: '/rastrear/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliverersRoute = AdminDeliverersRouteImport.update({
  id: '/deliverers',
  path: '/deliverers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedTimeRoute = AuthenticatedTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacotesRoute = AuthenticatedPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGanhosRoute = AuthenticatedGanhosRouteImport.update({
  id: '/ganhos',
  path: '/ganhos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregadoresRoute =
  AuthenticatedEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacotesDistribuirAlocacaoIdRoute =
  AuthenticatedPacotesDistribuirAlocacaoIdRouteImport.update({
    id: '/distribuir/$alocacaoId',
    path: '/distribuir/$alocacaoId',
    getParentRoute: () => AuthenticatedPacotesRoute,
  } as any)
const AuthenticatedPacotesAlocarOperacaoIdRoute =
  AuthenticatedPacotesAlocarOperacaoIdRouteImport.update({
    id: '/alocar/$operacaoId',
    path: '/alocar/$operacaoId',
    getParentRoute: () => AuthenticatedPacotesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/entregadores': typeof AuthenticatedEntregadoresRoute
  '/ganhos': typeof AuthenticatedGanhosRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/pacotes': typeof AuthenticatedPacotesRouteWithChildren
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/time': typeof AuthenticatedTimeRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deliverers': typeof AdminDeliverersRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/rastrear/$token': typeof RastrearTokenRoute
  '/pacotes/alocar/$operacaoId': typeof AuthenticatedPacotesAlocarOperacaoIdRoute
  '/pacotes/distribuir/$alocacaoId': typeof AuthenticatedPacotesDistribuirAlocacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/entregadores': typeof AuthenticatedEntregadoresRoute
  '/ganhos': typeof AuthenticatedGanhosRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/pacotes': typeof AuthenticatedPacotesRouteWithChildren
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/time': typeof AuthenticatedTimeRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deliverers': typeof AdminDeliverersRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/rastrear/$token': typeof RastrearTokenRoute
  '/pacotes/alocar/$operacaoId': typeof AuthenticatedPacotesAlocarOperacaoIdRoute
  '/pacotes/distribuir/$alocacaoId': typeof AuthenticatedPacotesDistribuirAlocacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/entregadores': typeof AuthenticatedEntregadoresRoute
  '/_authenticated/ganhos': typeof AuthenticatedGanhosRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRoute
  '/_authenticated/pacotes': typeof AuthenticatedPacotesRouteWithChildren
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/_authenticated/time': typeof AuthenticatedTimeRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deliverers': typeof AdminDeliverersRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/rastrear/$token': typeof RastrearTokenRoute
  '/_authenticated/pacotes/alocar/$operacaoId': typeof AuthenticatedPacotesAlocarOperacaoIdRoute
  '/_authenticated/pacotes/distribuir/$alocacaoId': typeof AuthenticatedPacotesDistribuirAlocacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/entregadores'
    | '/ganhos'
    | '/metricas'
    | '/notas'
    | '/ofertas'
    | '/pacotes'
    | '/pagamentos'
    | '/rotas'
    | '/time'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/deliverers'
    | '/admin/financial'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/settings'
    | '/rastrear/$token'
    | '/pacotes/alocar/$operacaoId'
    | '/pacotes/distribuir/$alocacaoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/entregadores'
    | '/ganhos'
    | '/metricas'
    | '/notas'
    | '/ofertas'
    | '/pacotes'
    | '/pagamentos'
    | '/rotas'
    | '/time'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/deliverers'
    | '/admin/financial'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/settings'
    | '/rastrear/$token'
    | '/pacotes/alocar/$operacaoId'
    | '/pacotes/distribuir/$alocacaoId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/entregadores'
    | '/_authenticated/ganhos'
    | '/_authenticated/metricas'
    | '/_authenticated/notas'
    | '/_authenticated/ofertas'
    | '/_authenticated/pacotes'
    | '/_authenticated/pagamentos'
    | '/_authenticated/rotas'
    | '/_authenticated/time'
    | '/admin/companies'
    | '/admin/dashboard'
    | '/admin/deliverers'
    | '/admin/financial'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/settings'
    | '/rastrear/$token'
    | '/_authenticated/pacotes/alocar/$operacaoId'
    | '/_authenticated/pacotes/distribuir/$alocacaoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  RastrearTokenRoute: typeof RastrearTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastrear/$token': {
      id: '/rastrear/$token'
      path: '/rastrear/$token'
      fullPath: '/rastrear/$token'
      preLoaderRoute: typeof RastrearTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deliverers': {
      id: '/admin/deliverers'
      path: '/deliverers'
      fullPath: '/admin/deliverers'
      preLoaderRoute: typeof AdminDeliverersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/time': {
      id: '/_authenticated/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AuthenticatedTimeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes': {
      id: '/_authenticated/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof AuthenticatedPacotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ganhos': {
      id: '/_authenticated/ganhos'
      path: '/ganhos'
      fullPath: '/ganhos'
      preLoaderRoute: typeof AuthenticatedGanhosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregadores': {
      id: '/_authenticated/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof AuthenticatedEntregadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes/distribuir/$alocacaoId': {
      id: '/_authenticated/pacotes/distribuir/$alocacaoId'
      path: '/distribuir/$alocacaoId'
      fullPath: '/pacotes/distribuir/$alocacaoId'
      preLoaderRoute: typeof AuthenticatedPacotesDistribuirAlocacaoIdRouteImport
      parentRoute: typeof AuthenticatedPacotesRoute
    }
    '/_authenticated/pacotes/alocar/$operacaoId': {
      id: '/_authenticated/pacotes/alocar/$operacaoId'
      path: '/alocar/$operacaoId'
      fullPath: '/pacotes/alocar/$operacaoId'
      preLoaderRoute: typeof AuthenticatedPacotesAlocarOperacaoIdRouteImport
      parentRoute: typeof AuthenticatedPacotesRoute
    }
  }
}

interface AuthenticatedPacotesRouteChildren {
  AuthenticatedPacotesAlocarOperacaoIdRoute: typeof AuthenticatedPacotesAlocarOperacaoIdRoute
  AuthenticatedPacotesDistribuirAlocacaoIdRoute: typeof AuthenticatedPacotesDistribuirAlocacaoIdRoute
}

const AuthenticatedPacotesRouteChildren: AuthenticatedPacotesRouteChildren = {
  AuthenticatedPacotesAlocarOperacaoIdRoute:
    AuthenticatedPacotesAlocarOperacaoIdRoute,
  AuthenticatedPacotesDistribuirAlocacaoIdRoute:
    AuthenticatedPacotesDistribuirAlocacaoIdRoute,
}

const AuthenticatedPacotesRouteWithChildren =
  AuthenticatedPacotesRoute._addFileChildren(AuthenticatedPacotesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEntregadoresRoute: typeof AuthenticatedEntregadoresRoute
  AuthenticatedGanhosRoute: typeof AuthenticatedGanhosRoute
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRoute
  AuthenticatedPacotesRoute: typeof AuthenticatedPacotesRouteWithChildren
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
  AuthenticatedTimeRoute: typeof AuthenticatedTimeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEntregadoresRoute: AuthenticatedEntregadoresRoute,
  AuthenticatedGanhosRoute: AuthenticatedGanhosRoute,
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRoute,
  AuthenticatedPacotesRoute: AuthenticatedPacotesRouteWithChildren,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
  AuthenticatedTimeRoute: AuthenticatedTimeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliverersRoute: typeof AdminDeliverersRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliverersRoute: AdminDeliverersRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  RastrearTokenRoute: RastrearTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
