/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedPacotesRouteImport } from './routes/_authenticated/pacotes'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedMetricasRouteImport } from './routes/_authenticated/metricas'
import { Route as AuthenticatedEntregadoresRouteImport } from './routes/_authenticated/entregadores'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPacotesRoute = AuthenticatedPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetricasRoute = AuthenticatedMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregadoresRoute =
  AuthenticatedEntregadoresRouteImport.update({
    id: '/entregadores',
    path: '/entregadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/entregadores': typeof AuthenticatedEntregadoresRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/entregadores': typeof AuthenticatedEntregadoresRoute
  '/metricas': typeof AuthenticatedMetricasRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/entregadores': typeof AuthenticatedEntregadoresRoute
  '/_authenticated/metricas': typeof AuthenticatedMetricasRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRoute
  '/_authenticated/pacotes': typeof AuthenticatedPacotesRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/admin/login': typeof AdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/entregadores'
    | '/metricas'
    | '/notas'
    | '/ofertas'
    | '/pacotes'
    | '/pagamentos'
    | '/rotas'
    | '/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/entregadores'
    | '/metricas'
    | '/notas'
    | '/ofertas'
    | '/pacotes'
    | '/pagamentos'
    | '/rotas'
    | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/entregadores'
    | '/_authenticated/metricas'
    | '/_authenticated/notas'
    | '/_authenticated/ofertas'
    | '/_authenticated/pacotes'
    | '/_authenticated/pagamentos'
    | '/_authenticated/rotas'
    | '/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes': {
      id: '/_authenticated/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof AuthenticatedPacotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metricas': {
      id: '/_authenticated/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof AuthenticatedMetricasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregadores': {
      id: '/_authenticated/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof AuthenticatedEntregadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEntregadoresRoute: typeof AuthenticatedEntregadoresRoute
  AuthenticatedMetricasRoute: typeof AuthenticatedMetricasRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRoute
  AuthenticatedPacotesRoute: typeof AuthenticatedPacotesRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEntregadoresRoute: AuthenticatedEntregadoresRoute,
  AuthenticatedMetricasRoute: AuthenticatedMetricasRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRoute,
  AuthenticatedPacotesRoute: AuthenticatedPacotesRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
